[package]
name = "mcc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
structopt = "0.3.26"
pnet = "0.30.0"
clap = "4.5.21"
inquire = "0.7.5"
colored = "2.1.0"
indicatif = "0.17.9"
